using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace MidtermII
{
    public static class Speeches
    {
        private static String ChuchillAddressToCongress = @"Members of the Senate and of the House of Representatives of the United States, I feel greatly honored that you should have thus invited me to enter the United States Senate Chamber and address the representatives of both branches of Congress. The fact that my American forebears have for so many generations played their part in the life of the United States, and that here I am, an Englishman, welcomed in your midst, makes this experience one of the most moving and thrilling in my life, which is already long and has not been entirely uneventful. I wish indeed that my mother, whose memory I cherish, across the vale of years, could have been here to see. By the way, I cannot help reflecting that if my father had been American and my mother British instead of the other way around, I might have got here on my own. In that case this would not have been the first time you would have heard my voice. In that case I should not have needed any invitation. But if I had it is hardly likely that it would have been unanimous. So perhaps things are better as they are. 

I may confess, however, that I do not feel quite like a fish out of water in a legislative assembly where English is spoken. I am a child of the House of Commons. I was brought up in my father's house to believe in democracy. Trust the people. That was his message. I used to see him cheered at meetings and in the streets by crowds of workingmen way back in those aristocratic Victorian days when as Disraeli said the world was for the few, and for the very few.

Therefore I have been in full harmony all my life with the tides which have flowed on both sides of the Atlantic against privilege and monopoly and I have steered confidently towards the Gettysburg ideal of government of the people, by the people, for the people.

I owe my advancement entirely to the House of Commons, whose servant I am. In my country as in yours public men are proud to be the servants of the State and would be ashamed to be its masters. The House of Commons, if they thought the people wanted it, could, by a simple vote, remove me from my office. But I am not worrying about it at all.

As a matter of fact I am sure they will approve very highly of my journey here, for which I obtained the King's permission, in order to meet the President of the United States and to arrange with him for all that mapping out of our military plans and for all those intimate meetings of the high officers of the armed services in both countries which are indispensable for the successful prosecution of the war.

I should like to say first of all how much I have been impressed and encouraged by the breadth of view and sense of proportion which I have found in all quarters over here to which I have had access. Anyone who did not understand the size and solidarity of the foundations of the United States, might easily have expected to find an excited, disturbed, self-cantered atmosphere, with all minds fixed upon the novel, startling, and painful episodes of sudden war as they hit America. After all, the United States have been attacked and set upon by three most powerfully armed dictator states, the greatest military power in Europe, the greatest military power in Asia-Japan, Germany and Italy have all declared and are making war upon you, and the quarrel is opened which can only end in their overthrow or yours.

But here in Washington in these memorable days I have found an Olympian fortitude which, far from being based upon complacency, is only the mask of an inflexible purpose and the proof of a sure, well-grounded confidence in the final outcome. We in Britain had the same feeling in our darkest days. We too were sure that in the end all would be well.

You do not, I am certain, underrate the severity of the ordeal to which you and we have still to be subjected. The forces ranged against us are enormous. They are bitter, they are ruthless. The wicked men and their factions, who have launched their peoples on the path of war and conquest, know that they will be called to terrible account if they cannot beat down by force of arms the peoples they have assailed. They will stop at nothing. They have a vast accumulation of war weapons of all kinds. They have highly trained and disciplined armies, navies and air services. They have plans and designs which have long been contrived and matured. They will stop at nothing that violence or treachery can suggest.

It is quite true that on our side our resources in manpower and materials are far greater than theirs. But only a portion of your resources are as yet mobilized and developed, and we both of us have much to learn in the cruel art of war. We have therefore without doubt a time of tribulation before us. In this same time, some ground will be lost which it will be hard and costly to regain. Many disappointments and unpleasant surprises await us. Many of them will afflict us before the full marshalling of our latent and total power can be accomplished.

For the best part of twenty years the youth of Britain and America have been taught that war was evil, which is true, and that it would never come again, which has been proved false. For the best part of twenty years, the youth of Germany, of Japan and Italy, have been taught that aggressive war is the noblest duty of the citizen and that it should be begun as soon as the necessary weapons and organization have been made. We have performed the duties and tasks of peace. They have plotted and planned for war. This naturally has placed us, in Britain, and now places you in the United States at a disadvantage which only time, courage and untiring exertion can correct.

We have indeed to be thankful that so much time has been granted to us. If Germany had tried to invade the British Isles after the French collapse in June, 1940, and if Japan had declared war on the British Empire and the United States at about the same date, no one can say what disasters and agonies might not have been our lot. But now, at the end of December, 1941, our transformation from easy-going peace to total war efficiency has made very great progress.

The broad flow of munitions in Great Britain has already begun. Immense strides have been made in the conversion of American industry to military purposes. And now that the United States is at war, it is possible for orders to be given every day which in a year or eighteen months hence will produce results in war power beyond anything which has been seen or foreseen in the dictator states.

Provided that every effort is made, that nothing is kept back, that the whole manpower, brain power, virility, valor and civic virtue of the English-speaking world, with all its galaxy of loyal, friendly or associated communities and states-provided that is bent unremittingly to the simple but supreme task, I think it would be reasonable to hope that the end of 1942 will see us quite definitely in a better position than we are now. And that the year 1943 will enable us to assume the initiative upon an ample scale.

Some people may be startled or momentarily depressed when, like your President, I speak of a long and a hard war. Our peoples would rather know the truth, somber though it be. And after all, when we are doing the noblest work in the world, not only defending our hearths and homes, but the cause of freedom in every land, the question of whether deliverance comes in 1942 or 1943 or 1944, falls into its proper place in the grand proportions of human history. Sure I am that this day, now, we are the masters of our fate. That the task which has been set us is not above our strength. That its pangs and toils are not beyond our endurance. As long as we have faith in our cause, and an unconquerable willpower, salvation will not be denied us. In the words of the Psalmist: He shall not be afraid of evil tidings. His heart is fixed, trusting in the Lord.

Not all the tidings will be evil. On the contrary, mighty strokes of war have already been dealt against the enemy-the glorious defense of their native soil by the Russian armies and people; wounds have been inflicted upon the Nazi tyranny and system which have bitten deep and will fester and inflame not only in the Nazi body but in the Nazi mind. The boastful Mussolini has crumpled already. He is now but a lackey and a serf, the merest utensil of his master's will. He has inflicted great suffering and wrong upon his own industrious people. He has been stripped of all his African empire. Abyssinia has been liberated. Our Armies of the East, which were so weak and ill-equipped at the moment of French desertion, now control all the regions from Teheran to Bengazi, and from Aleppo and Cyprus to the sources of the Nile.

For many months we devoted ourselves to preparing to take the offensive in Libya. The very considerable battle which has been proceeding there the last six weeks in the desert, has been most fiercely fought on both sides. Owing to the difficulties of supply upon the desert flank, we were never able to bring numerically equal forces to bear upon the enemy. Therefore we had to rely upon superiority in the numbers and qualities of tanks and aircraft, British and American. For the first time, aided by these-for the first time we have fought the enemy with equal weapons. For the first time we have made the Hun feel the sharp edge of those tools with which he has enslaved Europe. The armed forces of the enemy in Cyrenaica amounted to about 150,000 men, of whom a third were Germans. General Auchinleck set out to destroy totally that armed force, and I have every reason to believe that his aim will be fully accomplished. I am so glad to be able to place before you, members of the Senate and of the House of Representatives, at this moment when you are entering the war, the proof that with proper weapons and proper organization, we are able to beat the life out of the savage Nazi.

What Hitlerism is suffering in Libya is only a sample and a foretaste of what we have got to give him and his accomplices wherever this war should lead us in every quarter of the Globe.

There are good tidings also from blue water. The lifeline of supplies which joins our two nations across the ocean, without which all would fail,-that lifeline is flowing steadily and freely in spite of all that the enemy can do. It is a fact that the British Empire, which many thought eighteen months ago was broken and ruined, is now incomparably stronger and is growing stronger with every month.

Lastly, if you will forgive me for saying it, to me the best tidings of all-the United States, united as never before, has drawn the sword for freedom and cast away the scabbard.

All these tremendous facts have led the subjugated peoples of Europe to lift up their heads again in hope. They have put aside forever the shameful temptation of resigning themselves to the conqueror's will. Hope has returned to the hearts of scores of millions of men and women, and with that hope there burns the flame of anger against the brutal, corrupt invader. And still more fiercely burn the fires of hatred and contempt for the filthy Quislings whom he has suborned.

In a dozen famous ancient states, now prostrate under the Nazi yoke, the masses of the people, all classes and creeds, await the hour of liberation when they too will once again be able to play their part and strike their blows like men. That hour will strike. And its solemn peal will proclaim that night is past and that the dawn has come.

The onslaught upon us, so long and so secretly planned by Japan, has presented both our countries with grievous problems for which we could not be fully prepared. If people ask me, as they have a right to ask me in England, Why is it that you have not got an ample equipment of modern aircraft and army weapons of all kinds in Malaya and in the East Indies?-I can only point to the victory General Auchinleck has gained in the Libyan campaign. Had we diverted and dispersed our gradually-growing resources between Libya and Malaya, we should have been found wanting in both theaters.

If the United States has been found at a disadvantage at various points in the Pacific Ocean, we know well that that is to no small extent because of the aid which you have been giving to us in munitions for the defense of the British Isles and for the Libyan campaign, and above all because of your help in the Battle of the Atlantic, upon which all depends and which has in consequence been successfully and prosperously maintained.

Of course, it would have been much better, I freely admit, if we had had enough resources of all kinds to be at full strength at all threatened points. But considering how slowly and reluctantly we brought ourselves to large-scale preparations, and how long these preparations take, we had no right to expect to be in such a fortunate position.

The choice of how to dispose of our hitherto limited resources had to be made by Britain in time of war, and by the United States in time of peace. And I believe that history will pronounce that upon the whole, and it is upon the whole that these matters must be judged, that the choice made was right. Now that we are together, now that we are linked in a righteous comrade-ship of arms, now that our two considerable nations, each in perfect unity, have joined all their life-energies in a common resolve-a new scene opens upon which a steady light will glow and brighten.

Many people have been astonished that Japan should in a single day have plunged into war against the United States and the British Empire. We all wonder why, if this dark design with its laborious and intricate preparations had been so long filling their secret minds, they did not choose our moment of weakness eighteen months ago. Viewed quite dispassionately, in spite of the losses we have suffered and the further punishment we shall have to take, it certainly appears an irrational act. It is of course only prudent to assume that they have made very careful calculations and think they see their way through. Nevertheless, there may be another explanation.

We know that for many years past the policy of Japan has been dominated by secret societies of subalterns and junior officers of the army and navy, who have enforced their will upon successive Japanese cabinets and parliaments by the assassination of any Japanese statesmen who opposed or who did not sufficiently further their aggressive policy. It may be that these societies, dazzled and dizzy with their own schemes of aggression and the prospect of early victories, have forced their country-against its better judgment-into war. They have certainly embarked upon a very considerable undertaking.

After the outrages they have committed upon us at Pearl Harbor, in the Pacific Islands, in the Philippines, in Malaya and the Dutch East Indies, they must now know that the stakes for which they have decided to play are mortal. When we look at the resources of the United States and the British Empire compared to those of Japan; when we remember those of China, which have so long valiantly withstood invasion and tyranny-and when also we observe the Russian menace which hangs over Japan-it becomes still more difficult to reconcile Japanese action with prudence or even with sanity. What kind of a people do they think we are? Is it possible that they do not realize that we shall never cease to persevere against them until they have been taught a lesson which they and the world will never forget?

Members of the Senate, and members of the House of Representatives, I will turn for one moment more from the turmoil and convulsions of the present to the broader spaces of the future. Here we are together, facing a group of mighty foes who seek our ruin. Here we are together, defending all that to free men is dear. Twice in a single generation the catastrophe of world war has fallen upon us. Twice in our lifetime has the long arm of fate reached out across the oceans to bring the United States into the forefront of the battle.

If we had kept together after the last war, if we had taken common measures for our safety, this renewal of the curse need never have fallen upon us. Do we not owe it to ourselves, to our children, to tormented mankind, to make sure that these catastrophes do not engulf us for the third time?

It has been proved that pestilences may break out in the Old World which carry their destructive ravages into the New World, from which, once they are afoot, the New World can not escape. Duty and prudence alike command first that the germ-centers of hatred and revenge should be constantly and vigilantly served and treated in good time, and that an adequate organization should be set up to make sure that the pestilence can be controlled at its earliest beginnings, before it spreads and rages throughout the entire earth.

Five or six years ago it would have been easy, without shedding a drop of blood, for the United States and Great Britain to have insisted on the fulfilment of the disarmament clauses of the treaties which Germany signed after the Great War. And that also would have been the opportunity for assuring to the Germans those materials-those raw materials-which we declared in the Atlantic Charter should not be denied to any nation, victor or vanquished. The chance has passed, it is gone. Prodigious hammer-strokes have been needed to bring us together today.

If you will allow me to use other language, I will say that he must indeed have a blind soul who cannot see that some great purpose and design is being worked out here below of which we have the honor to be the faithful servants. It is not given to us to peer into the mysteries of the future. Still, I avow my hope and faith, sure and inviolate, that in the days to come the British and American peoples will, for their own safety and for the good of all, walk together in majesty, in justice and in peace.";

        private static String ChurchillInvasionOfFrance = @"The House should, I think, take formal cognisance of the liberation of Rome by the Allied Armies under the Command of General Alexander, with General Clark of the United States Service and General Oliver Leese in command of the fifth and Eighth Armies respectively. This is a memorable and glorious event, which rewards the intense fighting of the last five months in Italy. The original landing, made on January 22nd at Anzio, has, in the end, borne good fruit. In the first place, Hitler was induced to send to the south of Rome eight or nine divisions which he may well have need of elsewhere. Secondly, these divisions were repulsed, and their teeth broken, by the successful resistance of the Anzio bridgehead forces in the important battle which took place in the middle of February. The losses on both sides were heavy-the Allies losing about 20,000 men, and the Germans about 25,000 men. Thereafter, the Anzio bridgehead was considered by the enemy to be impregnable.

Meanwhile, the great regrouping of the main Army had to take place before the attacks could be renewed. These attacks were at first unsuccessful, and Cassino still blocked the advance. On May 11th, General Alexander began his present operation, and after unceasing and intense fighting by the whole of the Armies, broke into the enemy's lines and entered the Liri Valley. It is noteworthy that, counting from right to left, the whole of the Polish, British Empire, French, and United States Forces broke the German lines in front of them by frontal attack. That has an important bearing on other matters, which I shall come to before I sit down.

At what was judged the right moment the bridgehead force, which by this time had reached a total of nearly 150,000 men, fell upon the retiring enemy's flank and threatened his retreat. The junction of the main Armies with the bridgehead forces drove the enemy off his principal lines of retreat to the North, forcing a great part of his army to retire in considerable disorder with heavy losses, especially in material, through mountainous country. The Allied Forces, with great rapidity, were regrouped, with special emphasis on their left flank, which soon deployed against Rome after cutting the important highway. The American and other Forces of the Fifth Army broke through the enemy's last line and entered Rome, where the Allied troops have been received with joy by the population. This entry and liberation of Rome mean that we shall have the power to defend it from hostile air attack, and to deliver it from the famine with which it was threatened. However, General Alexander's prime object has never been the liberation of Rome, great as are the moral, political and psychological advantages of that episode. The Allied Forces, with the Americans in the van, are driving ahead, northwards, in relentless pursuit of the enemy. The destruction of the enemy army has been, throughout, the single aim, and they are now being engaged at the same time along the whole length of the line as they attempt to escape to the North. It is hoped that the 20,000 prisoners already taken will be followed by further captures in future, and that the condition of the enemy's army, which he has crowded into Southern Italy, will be decisively affected.

It would be futile to attempt to estimate our final gains at the present time. It is our duty, however, to pay the warmest tribute of gratitude and admiration to General Alexander for the skill with which he has handled this Army of so many different States and nations, and for the tenacity and fortitude with which he has sustained the long periods when success was denied. In General Clark the United States Army has found a fighting leader of the highest order, and the qualities of all Allied troops have shone in noble and unjealous rivalry. The great strength of the Air Forces at our disposal, as well as the preponderance in armour, has undoubtedly contributed in a notable and distinctive manner to the successes which have been achieved. We must await further developments in the Italian theatre before it is possible to estimate the magnitude and quality of our gains, great and timely though they certainly are.

I have also to announce to the House that during the night and the early hours of this morning the first of the series of landings in force upon the European Continent has taken place. In this case the liberating assault fell upon the coast of France. An immense armada of upwards of 4,000 ships, together with several thousand smaller craft, crossed the Channel. Massed airborne landings have been successfully effected behind the enemy lines, and landings on the beaches are proceeding at various points at the present time. The fire of the shore batteries has been largely quelled. The obstacles that were constructed in the sea have not proved so difficult as was apprehended. The Anglo-American Allies are sustained by about 11,000 firstline aircraft, which can be drawn upon as may be needed for the purposes of the battle. I cannot, of course, commit myself to any particular details. Reports are coming in in rapid succession. So far the Commanders who are engaged report that everything is proceeding according to plan. And what a plan! This vast operation is undoubtedly the most complicated and difficult that has ever taken place. It involves tides, wind, waves, visibility, both from the air and the sea standpoint, and the combined employment of land, air and sea forces in the highest degree of intimacy and in contact with conditions which could not and cannot be fully foreseen.

There are already hopes that actual tactical surprise has been attained, and we hope to furnish the enemy with a succession of surprises during the course of the fighting. The battle that has now begun will grow constantly in scale and in intensity for many weeks to come, and I shall not attempt to speculate upon its course. This I may say, however. Complete unity prevails throughout the Allied Armies. There is a brotherhood in arms between us and our friends of the United States. There is complete confidence in the supreme commander, General Eisenhower, and his lieutenants, and als6 in the commander of the Expeditionary Force, General Montgomery. The ardour and spirit of the troops, as I saw myself, embarking in these last few days was splendid to witness. Nothing that equipment, science or forethought could do has been neglected, and the whole process of opening this great new front will be pursued with the utmost resolution both by the commanders and by the United States and British Governments whom they serve. [Editor's Note: Mr. Churchill added the following statement later in the day] : I have been at the centres where the latest information is received, and I can state to the House that this operation is proceeding in a thoroughly satisfactory manner. Many dangers and difficulties which at this time last night appeared extremely formidable are behind us. The passage of the sea has been made with far less loss than we apprehended. The resistance of the batteries has been greatly weakened by the bombing of the Air Force, and the superior bombardment of our ships quickly reduced their fire to dimensions which did not affect the problem. The landings of the troops on a broad front, both British and American- -Allied troops, I will not give lists of all the different nationalities they represent-but the landings along the whole front have been effective, and our troops have penetrated, in some cases, several miles inland. Lodgments exist on a broad front.

The outstanding feature has been the landings of the airborne troops, which were on a scale far larger than anything that has been seen so far in the world. These landings took place with extremely little loss and with great accuracy. Particular anxiety attached to them, because the conditions of light prevailing in the very limited period of the dawn-just before the dawn-the conditions of visibility made all the difference. Indeed, there might have been something happening at the last minute which would have prevented airborne troops from playing their part. A very great degree of risk had to be taken in respect of the weather.

But General Eisenhower's courage is equal to all the necessary decisions that have to be taken in these extremely difficult and uncontrollable matters. The airborne troops are well established, and the landings and the follow-ups are all proceeding with much less loss-very much less-than we expected. Fighting is in progress at various points. We captured various bridges which were of importance, and which were not blown up. There is even fighting proceeding in the town of Caen, inland. But all this, although a very valuable first step-a vital and essential first step-gives no indication of what may be the course of the battle in the next days and weeks, because the enemy will now probably endeavour to concentrate on this area, and in that event heavy fighting will soon begin and will continue without end, as we can push troops in and he can bring other troops up. It is, therefore, a most serious time that we enter upon. Thank God, we enter upon it with our great Allies all in good heart and all in good friendship.";

        private static String ChurchillFiftyYearsHence = @"The great mass of human beings, absorbed in the toils, cares and activities of life, are only dimly conscious of the pace at which mankind has begun to travel. We look back a hundred years and see that great changes have taken place. We look back fifty years and see that the speed is constantly quickening. This present century has witnessed an enormous revolution in material things, in scientific appliances, in political institutions, in manners and customs. The greatest change of all is the least perceptible by individuals: it is the far greater numbers which in every civilized country participate in the fuller life of man. 'In those days,' said Disraeli, writing at the beginning of the nineteenth century, 'England was for the few and for the very few.' 'The twice two thousand for whom,' wrote Byron, 'the world is made' have given place to many millions for whom existence has become larger, safer, more varied, more full of hope and choice. In the United States scores of millions have lifted themselves above primary necessities and comforts, and aspire to culture - at least for their children. Europe, though stunned and lacerated by Armageddon, presents a similar if less general advance. We all take the modern conveniences and facilities as they are offered to us without being grateful or consciously happier. But we simply could not live if they were taken away. We assume that progress will be constant. 'This 'ere progress,' Mr Wells makes one of his characters remark, 'keeps going on. It's wonderful 'ow it keeps going on.' It is also very fortunate, for if it stopped or were reversed, there would be the catastrophe of unimaginable horror. Mankind has gone too far to go back, and is moving too fast to stop. There are too many people maintained, not merely in comfort but in existence, by processes unknown a century ago, for us to afford even a temporary check, still less a general setback, without experiencing calamity in its most frightful form.

When we look back beyond a hundred years over the long trails of history, we see immediately why the age we live in differs from all other ages in human annals. Mankind has sometimes travelled forwards and sometimes backwards, or has stood still even for hundreds of years. It remained stationary in India and in China for thousands of years. What is it that has produced this new prodigious speed of man? Science is the cause. Her once feeble vanguards, often trampled down, often perishing in isolation, have now become a vast organized united class-conscious army marching forward upon all the fronts towards objectives none may measure or define. It is a proud, ambitious army which cares nothing for all the laws that men have made; nothing for their most timehonoured customs, or most dearly cherished beliefs, or deepest instincts. It is this power called Science which has laid hold of us, conscripted us into its regiments and batteries, set us to work upon its highways and in its arsenals; rewarded us for our services, healed us when we were wounded, trained us when we were young, pensioned us when we were worn out. None of the generations of men before the last two or three were ever gripped for good or ill and handled like this.

Man in the earliest stages lived alone and avoided his neighbours with as much anxiety and probably as much reason as he avoided the fierce flesh-eating beasts that shared his forests. With the introduction of domestic animals the advantages of co-operation and the division of labour became manifest. In the neolithic times when cereals were produced and agriculture developed, the bleak hungry period whilst the seeds were germinating beneath the soil involved some form of capitalism and the recognition of those special rights of landed proprietors the traces of which are still visible in our legislation. Each stage involved new problems legal, sociological and moral. But progress only crawled, and often rested for a thousand years or so.

The two ribbon States in the valley of the Nile and the Euphrates produced civilizations as full of pomp and circumstance and more stable than any the world has ever known. Their autocracies and hierarchies were founded upon the control and distribution of water and corn. The rulers held the people in an efficiency of despotism never equalled till Soviet Russia was born. They had only to cut off or stint the water in the canals to starve or subjugate rebellious provinces. This, apart from their granaries, gave them powers at once as irresistible and as capable of intimate regulation as the control of all food supplies gives to the Bolshevik commissars. Safe from internal trouble, they were vulnerable only to external attack. But in these states man had not learnt to catalyse the forces of nature. The maximum power available was the sum of the muscular efforts of all the inhabitants. Later empires, scarcely less imposing but far less stable, rose and fell. In the methods of production and communication, in the modes of getting food and exchanging goods, there was less change between the time of Sargon and the time of Louis XIV than there has been between the accession of Queen Victoria and the present day. Darius could probably send a message from Susa to Sardis faster than Philip II could transmit an order from Madrid to Brussels. Sir Robert Peel, summoned in 1841 from Rome to form a government in London, took the same time as the Emperor Vespasian when he had to hasten to his province of Britain. The bathrooms of the palaces of Minos were superior to those of Versailles. A priest from Thebes would probably have felt more at home at the Council of Trent two thousand years after Thebes had vanished than Sir Isaac Newton at a modern undergraduate physical society, or George Stephenson in the Institute of Electrical Engineers. The changes have been so sudden and so gigantic that no period in history can be compared with the last century. The past no longer enables us even dimly to measure the future.

The most wonderful of all modern prophecies is found in Tennyson's 'Locksley Hall':

For I dipt into the future, far as human eye could see,
Saw the Vision of the world, and all the wonder that would be; 
Saw the heavens fill with commerce, argosies of magic sails, 
Pilots of the purple twilight, dropping down with costly bales; 
Heard the heavens fill with shouting, and there rain'd a ghastly dew 
From the nations' airy navies grappling in the central blue; 
Far along the world-wide whisper of the south-wind rushing warm 
With the standards of the peoples plunging thro' the thunderstorm; 
Till the war-drum throbb'd no longer, and the battle-flags were furl'd 
In the Parliament of man, the Federation of the world. 
Slowly comes a hungry people, as a lion creeping nigher, 
Glares at one that nods and winks behind a slowly-dying fire.

These six couplets of prediction, written eighty years ago, have already been fulfilled. The conquest of the air for commerce and war, the League of Nations, the Communist movement -- all divined in their true sequence by the great Victorian -- all now already in the history books and stirring the world around us today! We may search the Scriptures in vain for such precise and swiftly vindicated forecasts of the future. Jeremiah and Isaiah dealt in dark and cryptic parables pointing to remote events and capable of many varied interpretations from time to time. A Judge, a Prophet, a Redeemer would arise to save His Chosen People; and from age to age the Jews asked, disputing, 'Art thou he that should come or do we look for another?' But 'Locksley Hall' contains an exact foretelling of stupendous events, which many of those who knew the writer lived to see and endure! The dawn of the Victorian era opened the new period of man; and the genius of the poet pierced the veil of the future.

There are two processes which we adopt consciously or unconsciously when we try to prophesy. We can seek a period in the past whose conditions resemble as closely as possible those of our day, and presume that the sequel to that period will, save for some minor alterations, be repeated. Secondly, we can survey the general course of development in our immediate past, and endeavour to prolong it into the near future. The first is the method of the historian; the second that of the scientist. Only the second is open to us now, and this only in a partial sphere. By observing all that Science has achieved in modern times, and the knowledge and power now in her possession, we can predict with some assurance the inventions and discoveries which will govern our future. We can but guess, peering through a glass darkly, what reactions these discoveries and their applications will produce upon the habits, the outlook and the spirit of men.

Whereas formerly the utmost power that man could guide and control was a team of horses or a galleyful of slaves, or possibly, if they could be sufficiently drilled and harnessed, a gang of labourers like the Israelites in Egypt; it is today already possible to control accurately from the bridge of a battle cruiser all the power of hundreds of thousands of men, or to set off with one finger a mine capable in an instant of destroying the work of thousands of man-years. These changes are due to the substitution of molecular energy for muscular energy, and its direction and control by an elaborate, beautifully perfected apparatus. These immense new sources of power, and the fact that they can be wielded by a single individual, have made possible novel methods of mining and metallurgy, new modes of transport and undreamed-of machinery. These in their turn enable the molecular sources of power to be extended and used more efficiently. They facilitate also the improvement of ancient methods. They substitute the hundred-thousandkilowatt turbo-generators at Niagara for the mill-wheel of our forefathers. Each invention acted and reacted on other inventions, and with ever-growing rapidity that vast structure of technical achievement was raised which separates the civilization of today from all that the past has known.

There is no doubt that this evolution will continue at an increasing rate. We know enough to be sure that the scientific achievements of the next fifty years will be far greater, more rapid and more surprising, than those we have already experienced. The slide-lathe enabled machines of precision to be made, and the power of steam rushed out upon the world. And through the steam-clouds flashed the dazzling lightning of electricity. But this is only a beginning. High authorities tell us that new sources of power, vastly more important than any we yet know, will surely be discovered. Nuclear energy is incomparably greater than the molecular energy which we use today. The coal a man can get in a day can easily do five hundred times as much work as the man himself. Nuclear energy is at least one million times more powerful still. If the hydrogen atoms in a pound of water could be prevailed upon to combine together and form helium, they would suffice to drive a thousandhorsepower engine for a whole year. If the electrons, those tiny planets of the atomic systems, were induced to combine with the nuclei in the hydrogen the horsepower liberated would be 120 times greater still. There is no question among scientists that this gigantic source of energy exists. What is lacking is the match to set the bonfire alight, or it may be the detonator to cause the dynamite to explode. The Scientists are looking for this.

The discovery and control of such sources of power would cause changes in human affairs incomparably greater than those produced by the steam-engine four generations ago. Schemes of cosmic magnitude would become feasible. Geography and climate would obey our orders. Fifty thousand tons of water, the amount displaced by the Berengaria, would, if exploited as described, suffice to shift Ireland to the middle of the Atlantic. The amount of rain falling yearly upon the Epsom racecourse would be enough to thaw all the ice at the Arctic and Antarctic poles. The changing of one element into another by means of temperatures and pressures would be far beyond our present reach, would transform beyond all description our standards of values. Materials thirty times stronger than the best steel would create engines fit to bridle the new forms of power. Communications and transport by land, water and air would take unimaginable forms, if, as is in principle possible, we could make an engine of 600 horsepower, weighing 20 lb and carrying fuel for a thousand hours in a tank the size of a fountain-pen. Wireless telephones and television, following naturally upon their present path of development, would enable their owner to connect up with any room similarly installed, and hear and take part in the conversation as well as if he put his head in through the window. The congregation of men in cities would become superfluous. It would rarely be necessary to call in person on any but the most intimate friends, but if so, excessively rapid means of communication would be at hand. There would be no more object in living in the same city with one's neighbour than there is today in living with him in the same house. The cities and the countryside would become indistinguishable. Every home would have its garden and its glade.

Up till recent times the production of food has been the prime struggle of man. That war is won. There is no doubt that the civilized races can produce or procure all the food they require. Indeed some of the problems which vex us today are due to the production of wheat by white men having exceeded their own needs, before yellow men, brown men and black men have learnt to demand and become able to purchase a diet superior to rice. But food is at present obtained almost entirely from the energy of the sunlight. The radiation from the sun produces from the carbonic acid in the air more or less complicated carbon compounds which give us our plants and vegetables. We use the latent chemical energy of these to keep our bodies warm; we convert it into muscular effort. We employ it in the complicated processes of digestion to repair and replace the wasted cells of our bodies. Many people, of course, prefer food in what the vegetarians call 'the secondhand form', i.e. after it has been digested and converted into meat for us by domestic animals kept for this purpose. In all these processes, however, ninety-nine parts of the solar energy are wasted for every part used.

Even without the new sources of power great improvements are probable here. Microbes, which at present convert the nitrogen of the air into the proteins by which animals live, will be fostered and made to work under controlled conditions, just as yeast is now. New strains of microbes will be developed and made to do a great deal of our chemistry for us. With a greater knowledge of what are called hormones, i.e. the chemical messengers in our blood, it will be possible to control growth. We shall escape the absurdity of growing a whole chicken in order to eat the breast or wing, by growing these parts separately under a suitable medium. Synthetic food will, of course, also be used in the future. Nor need the pleasures of the table be banished. That gloomy Utopia of tabloid meals need never be invaded. The new foods will from the outset be practically indistinguishable from the natural products, and any changes will be so gradual as to escape observation.

If the gigantic new sources of power become available, food will be produced without recourse to sunlight. Vast cellars in which artificial radiation is generated may replace the cornfields or potato-patches of the world. Parks and gardens will cover our pastures and ploughed fields. When the time comes there will be plenty of room for the cities to spread themselves again.

But equally startling developments lie already just beyond our finger-tips in the breeding of human beings and the shaping of human nature. It used to be said, 'Though you have taught the dog more tricks, you cannot alter the breed of the dog.' But that is no longer true. A few years ago London was surprised by a play called Rossum's Universal Robots. The production of such beings may well be possible within fifty years. They will not be made, but grown under glass. There seems little doubt that it will be possible to carry out in artificial surroundings the entire cycle which now leads to the birth of a child. Interference with the mental development of such beings, expert suggestion and treatment in the earlier years, Fifty Years Hence Reprinted by kind permission of Mr. Winston S. Churchill Page 5 of 6 would produce beings specialized to thought or toil. The production of creatures, for instance, which have admirable physical development, with their mental endowment stunted in particular directions, is almost within the range of human power. A being might be produced capable of tending a machine but without other ambitions. Our minds recoil from such fearful eventualities, and the laws of a Christian civilization will prevent them. But might not lop-sided creatures of this type fit in well with the Communist doctrines of Russia? Might not the Union of Soviet Republics armed with all the power of science find it in harmony with all their aims to produce a race adapted to mechanical tasks and with no other ideas but to obey the Communist State? The present nature of man is tough and resilient. It casts up its sparks of genius in the darkest and most unexpected places. But Robots could be made to fit the grisly theories of Communism. There is nothing in the philosophy of Communists to prevent their creation.

I have touched upon this sphere only lightly, but with the purpose of pointing out that, in a future which our children may live to see, powers will be in the hands of men altogether different from any by which human nature has been moulded. Explosive forces, energy, materials, machinery will be available upon a scale which can annihilate whole nations. Despotisms and tyrannies will be able to prescribe the lives and even the wishes of their subjects in a manner never known since time began. If to these tremendous and awful powers is added the pitiless sub-human wickedness which we now see embodied in one of the most powerful reigning governments, who shall say that the world itself will not be wrecked, or indeed that it ought not to be wrecked? There are nightmares of the future from which a fortunate collision with some wandering star, reducing the earth to incandescent gas, might be a merciful deliverance.

It is indeed a descent almost to the ridiculous to contemplate the impact of the tremendous and terrifying discoveries which are approaching upon the structure of Parliamentary institutions. How can we imagine the whole mass of the people being capable of deciding by votes at elections upon the right course to adopt amid these cataclysmic changes? Even now the Parliaments of every country have shown themselves quite inadequate to deal with the economic problems which dominate the affairs of every nation and of the world. Before these problems the claptrap of the hustings and the stunts of the newspapers wither and vanish away. Democracy as a guide or motive to progress has long been known to be incompetent. None of the legislative assemblies of the great modern states represents in universal suffrage even a fraction of the strength or wisdom of the community. Great nations are no longer led by their ablest men, or by those who know most about their immediate affairs, or even by those who have a coherent doctrine. Democratic governments drift along the line of least resistance, taking short views, paying their way with sops and doles, and smoothing their path with pleasant-sounding platitudes. Never was there less continuity or design in their affairs, and yet towards them are coming swiftly changes which will revolutionize for good or ill not only the whole economic structure of the world but the social habits and moral outlook of every family. Only the Communists have a plan and a gospel. It is a plan fatal to personal freedom and a gospel founded upon Hate.

Certain it is that while men are gathering knowledge and power with ever-increasing and measureless speed, their virtues and their wisdom have not shown any notable improvement as the centuries have rolled. The brain of a modern man does not differ in essentials from that of the human beings who fought and loved here millions of years ago. The nature of man has remained hitherto practically unchanged. Under sufficient stress -- starvation, terror, warlike passion, or even cold intellectual frenzy -- the modern man we know so well will do the most terrible deeds, and his modern woman will back him up. At the present moment the civilizations of many different ages co-exist together in the world, and their representatives meet and converse. Englishmen, Frenchmen, or Americans with ideas abreast of the twentieth century do business with Indians or Chinese whose civilizations were crystallized several thousands of years ago. We have the spectacle of the powers and weapons of man far outstripping the march of his intelligence; we have the march of his intelligence proceeding far more rapidly than the development of his nobility. We may well find ourselves in the presence of 'the strength of civilization without its mercy'.

It is therefore above all things important that the moral philosophy and spiritual conceptions of men and nations should hold their own amid these formidable scientific evolutions. It would be much better to call a halt in material progress and discovery rather than to be mastered by our own apparatus and the forces which it directs. There are secrets too mysterious for man in his present state to know, secrets which, once penetrated, may be fatal to human happiness and glory. But the busy hands of the scientists are already fumbling with the keys of all the chambers hitherto forbidden to mankind. Without an equal growth of Mercy, Pity, Peace and Love, Science herself may destroy all that makes human life majestic and tolerable. There never was a time when the inherent virtue of human beings required more strong and confident expression in daily life; there never was a time when the hope of immortality and the disdain of earthly power and achievement were more necessary for the safety of the children of men.

After all, this material progress, in itself so splendid, does not meet any of the real needs of the human race. I read a book the other day which traced the history of mankind from the birth of the solar system to its extinction. There were fifteen or sixteen races of men which in succession rose and fell over periods measured by tens of millions of years. In the end a race of beings was evolved which had mastered nature. A state was created whose citizens lived as long as they chose, enjoyed pleasures and sympathies incomparably wider than our own, navigated the interplanetary spaces, could recall the panorama of the past and foresee the future. But what was the good of all that to them? What did they know more than we know about the answers to the simple questions which man has asked since the earliest dawn of reason -- 'Why are we here? What is the purpose of life? Whither are we going?' No material progress, even though it takes shapes we cannot now conceive, or however it may expand the faculties of man, can bring comfort to his soul. It is this fact, more wonderful than any that Science can reveal, which gives the best hope that all will be well. Projects undreamed-of by past generations will absorb our immediate descendants; forces terrific and devastating will be in their hands; comforts, activities, amenities, pleasures will crowd upon them, but their hearts will ache, their lives will be barren, if they have not a vision above material things. And with the hopes and powers will come dangers out of all proportion to the growth of man's intellect, to the strength of his character or to the efficacy of his institutions. Once more the choice is offered between Blessing and Cursing. Never was the answer that will be given harder to foretell.";

        private static String LincolnHouseDivided = @"Mr. President and Gentlemen of the Convention.

If we could first know where we are, and whither we are tending, we could better judge what to do, and how to do it.

We are now far into the fifth year, since a policy was initiated, with the avowed object, and confident promise, of putting an end to slavery agitation.

Under the operation of that policy, that agitation has not only, not ceased, but has constantly augmented.

In my opinion, it will not cease, until a crisis shall have been reached, and passed -

A house divided against itself cannot stand.

        I believe this government cannot endure, permanently half slave and half free.

            I do not expect the Union to be dissolved - I do not expect the house to fall - but I do expect it will cease to be divided.

            It will become all one thing, or all the other.

            Either the opponents of slavery, will arrest the further spread of it, and place it where the public mind shall rest in the belief that it is in course of ultimate extinction; or its advocates will push it forward till it shall become alike lawful in all the States, old as well as new-North as well as South.

            Have we no tendency to the latter condition?

        Let any one who doubts, carefully contemplate that now almost complete legal combination - piece of machinery so to speak- compounded of the Nebraska doctrine, and the Dred Scott decision.Let him consider not only what work the machinery is adapted to do, and how well adapted; but also, let him study the history of its construction, and trace, if he can, or rather fail, if he can, to trace the evidences of design and concert of action, among its chief bosses, from the beginning.

            But, so far, Congress only, had acted; and an indorsement by the people, real or apparent, was indispensable, to save the point already gained, and give chance for more.

            The new year of 1854 found slavery excluded from more than half the State by State Constitutions, and from most of the national territory by congressional prohibition.

            Four days later, commenced the struggle, which ended in repealing that congressional prohibition.

            This opened all the national territory to slavery; and was the first point gained.

            This necessity had not been overlooked; but had been provided for, as well as might be, in the notable argument of squatter sovereignty, otherwise called sacred right of self government, which latter phrase, though expressive of the only rightful basis of any government, was so perverted in this attempted use of it as to amount to just this: That if any one man, choose to enslave another, no third man shall be allowed to object.

        That argument was incorporated into the Nebraska bill itself, in the language which follows: It being the true intent and meaning of this act not to legislate slavery into any Territory or State, nor to exclude it therefrom; but to leave the people thereof perfectly free to form and regulate their domestic institutions in their own way, subject only to the Constitution of the United States.

        Then opened the roar of loose declamation in favor of Squatter Sovereignty, and Sacred right of self government.

        But, said opposition members, let us be more specific- let us amend the bill so as to expressly declare that the people of the Territory may exclude slavery.Not we, said the friends of the measure; and down they voted the amendment.

            While the Nebraska bill was passing through congress, a law case, involving the question of a negro's freedom, by reason of his owner having voluntarily taken him first into a free State and then a territory covered by the congressional prohibition, and held him as a slave for a long time in each, was passing through the U.S. Circuit Court for the District of Missouri; and both Nebraska bill and law suit were brought to a decision in the same month of May, 1854. The negro's name was Dred Scott, which name now designates the decision finally made in the case.

        Before the then next Presidential election, the law case came to, and was argued in the Supreme Court of the United States; but the decision of it was deferred until after the election.Still, before the election, Senator Trumbull, on the floor of the Senate, requests the leading advocate of the Nebraska bill to state his opinion whether the people of a territory can constitutionally exclude slavery from their limits; and the latter answers, That is a question for the Supreme Court.

        The election came.Mr.Buchanan was elected, and the indorsement, such as it was, secured. That was the second point gained.The indorsement, however, fell short of a clear popular majority by nearly four hundred thousand votes, and so, perhaps, was not over-whelmingly reliable and satisfactory.


            The outgoing President, in his last annual message, as impressively as possible echoed back upon the people the weight and authority of the indorsement.

            The Supreme Court met again, did not announce their decision, but ordered a re-argument.

            The Presidential inauguration came, and still no decision of the court; but the incoming President, in his inaugural address, fervently exhorted the people to abide by the forthcoming decision, whatever it might be.

            Then, in a few days, came the decision.

            The reputed author of the Nebraska bill finds an early occasion to make a speech at this capitol indorsing the Dred Scott Decision, and vehemently denouncing all opposition to it.

            The new President, too, seizes the early occasion of the Silliman letter to indorse and strongly construe that decision, and to express his astonishment than any different view had ever been entertained.

            At length a squabble springs up between the President and the author of the Nebraska bill, on the mere question of fact, whether the Lecompton constitution was or was not, in any just sense, made by the people of Kansas; and in that quarrel the latter declares that all he wants is a fair vote for the people, and that he cares not whether slavery be voted down or voted up.I do not understand his declaration that he cares not whether slavery be voted down or voted up, to be intended by him other than as an apt definition of the policy he would impress upon the public mind - the principle for which he declares he has suffered much, and is ready to suffer to the end.

            And well may he cling to that principle.If he has any parental feeling, well may he cling to it. That principle, is the only shred left of his original Nebraska doctrine.Under the Dred Scott decision, squatter sovereignty squatted out of existence, tumbled down like temporary scaffolding - like the mold at the foundry served through one blast and fell back into loose sand - helped to carry an election, and then was kicked to the winds.His late joint struggle with the Republicans, against the Lecompton Constitution, involves nothing of the original Nebraska doctrine.That struggle was made on a point, the right of a people to make their own constitution, upon which he and the Republicans have never differed.

            The several points of the Dred Scott decision, in connection with Senator Douglas' care not policy, constitute the piece of machinery, in its present state of advancement.


            The working points of that machinery are:


        First, that no negro slave, imported as such from Africa, and no descendant of such slave can ever be a citizen of any State, in the sense of that term as used in the Constitution of the United States.


            This point is made in order to deprive the negro, in every possible event, of the benefit of that provision of the United States Constitution, which declares that -

        The citizens of each State shall be entitled to all privileges and immunities of citizens in the several States.

        Secondly, that subject to the Constitution of the United States, neither Congress nor a Territorial Legislature can exclude slavery from any United States Territory.

            This point is made in order that individual men may fill up the territories with slaves, without danger of losing them as property, and thus enhance the chances of permanency to the institution through all the future.

            Thirdly, that whether the holding a negro in actual slavery in a free State, makes him free, as against the holder, the United States courts will not decide, but will leave to be decided by the courts of any slave State the negro may be forced into by the master.

            This point is made, not to be pressed immediately; but, if acquiesced in for a while, and apparently indorsed by the people at an election, then ro sustain the logical conclusion that what Dred Scott's master might lawfully do with Dred Scott, in the free State of Illinois, every other master may lawfully do with any other one or one thousand slaves, in Illinois, or in any other free State.

            Auxiliary to all this, and working hand in hand with it, the Nebraska doctrine, or what is left of it, is to educate and mould public opinion, at least Northern public opinion, to not care whether slavery is voted down or voted up.

            This shows exactly where we now are; and partially also, whither we are tending.

            It will throw additional light on the latter, to go back, and run the mind over the string of historical facts already stated. Several things will now appear less dark and mysterious than they did when they were transpiring. The people were to be left perfectly free subject only to the Constitution. What the Constitution had to do with it, outsides could not then see.Plainly enough now, it was an exactly fitted nitch for the Dred Scott decision to afterward come in, and declare that perfect freedom of the people, to be just no freedom at all.

            Why was the amendment, expressly declaring the right of the people to exclude slavery, voted down? Plainly enough now, the adoption of it, would have spoiled the nitch for the Dred Scott decision.

            Why was the court decision held up? Why, even a Senator's individual opinion withheld, till after the Presidential election? Plainly enough now, the speaking out then would have damaged the perfectly free argument upon which the election was to be carried.

            Why the outgoing President's felicitation on the indorsement? Why the delay of a reargument? Why the incoming President's advance exhortation in favor of the decision?

        These things look like the cautious patting and petting of a spirited horse, preparatory to mounting him, when it is dreaded that he may give the rider a fall.

            Any why the hasty after indorsements of the decision by the President and others?

        We cannot absolutely know that all these exact adaptations are the result of preconcert. But when we see a lot of framed timbers, different potions of which we know have been gotten out at different times and places and by different workmen,- Stephen, Franklin, Roger and James, for instance-and we see these timbers joined together, and see they exactly make the frame of a house or a mill, all the tenons and mortieses exactly fitting, and all the lengths and proportions of the different pieces exactly adapted to their respective places, and not a piece too many or too few-not omitting even scaffolding-or, if a single piece be lacking, we see the place in the frame exactly fitted and prepared to yet bring such piece in-in such a case, we find it impossible not to believe that Stephen and Franklin and Roger and James all understood one another from the beginning, and all worked upon a common plan or draft drawn up before the first lick was struck.

            It should not be overlooked that, by the Nebraska bill, the people of State as well as Territory, were to be left perfectly free subject only to the Constitution.

        Why mention a State? They were legislating for territories, and not for or about States.Certainly the people of a State are and ought to be subject to the Constitution of the United States; but why is mention of this lugged into this merely territorial law? Why are the people of a territory and the people of a state therein lumped together, and their relation to the Constitution therein treated as being precisely the same?

        While the opinion of the Court, by Chief Justice Taney, in the Dred Scott case, and the separate opinions of all the concurring Judges, expressly declare that the Constitution of the United States neither permits Congress nor a territorial legislature to exclude slavery from any United States territory, they all omit to declare whether or not the same Constitution permits a state, or the people of a State to exclude it.

            Possibly, this is a mere omission; but who can be quite sure, if McLean or Curtis had sought to get into the opinion a declaration of unlimited power in the people of a state to exclude slavery from their limits, just as Chase and Mace sought to get such declaration, in behalf of the people of a territory, into the Nebraska bill-I ask, who can be quite sure that it would not have been voted down, in the one case, as it had been in the other?

        The nearest approach to the point of declaring the power of a State over slavery, is made by Judge Nelson.He approaches it more than once, using the precise idea, and almost the language too, of the Nebraska act.On one occasion his exact language is, except in cases where the power is restrained by the Constitution of the United States, the law of the State is supreme over the subject of slavery within its jurisdiction.

        In what cases the power of the states is so restrained by the U.S.Constitution is left an open question, precisely as the same question, as to the restraint on the power of the territories was left open in the Nebraska act.Put that and that together, and we have another nice little nitch, which we may, ere long, see filled with another Supreme Court decision, declaring that the Constitution of the United States does not permit a state to exclude slavery from its limits.

            And this may be expected if the doctrine of care not whether slavery be voted down or voted up, shall gain upon the public mind sufficiently to give promise that such a decision can be maintained when made.

            Such a decision is all that slavery now lacks of being alike lawful in all the States.

            Welcome or unwelcome, such decision is probably coming, and will soon be upon us, unless the power of the present political dynasty shall be met and overthrown.

            We shall lie down pleasantly dreaming that the people of Missouri are on the verge of making their State free; and we shall awake to the reality, instead, that the Supreme Court has made Illinois a slave State.

            To meet and overthrow the power of that dynasty, is the work now before all those who would prevent that consummation.

            That is what we have to do.


        But how can we best do it?

            There are those who denounce us openly to their own friends, and yet whisper us softly, that Senator Douglas is the aptest instrument there is, with which to effect that object. They do not tell us, nor has he told us, that he wishes any such object to be effected. They wish us to infer all, from the facts, that he now has a little quarrel with the present head of the dynasty; and that he has regularly voted with us, on a single point, upon which, he and we, have never differed.

            They remind us that he is a great man, and that the largest of us are very small ones. Let this be granted. But a living dog is better than a dead lion. Judge Douglas, if not a dead lion for this work, is at least a caged and toothless one.How can he oppose the advance of slavery? He don't care anything about it. His avowed mission is impressing the public heart to care nothing about it.


            A leading Douglas Democratic newspaper thinks Douglas' superior talent will be needed to resist the revival of the African slave trade.


            Does Douglas believe an effort to revive that trade is approaching? He has not said so. Does he really think so? But if it is, how can he resist it? For years he has labored to prove it a sacred right of white men to take negro slaves into the new territories.Can he possibly show that it is less a sacred right to buy them where they can be brought cheapest? And, unquestionably they can be bought cheaper in Africa than in Virginia.

            He has done all in his power to reduce the whole question of slavery to one of a mere right of property; and as such, how can he oppose the foreign slave trade-how can he refuse that trade in that property shall be perfectly free  unless he does it as a protection to the home production? And as the home producers will probably not ask the protection, he will be wholly without a ground of opposition.

            Senator Douglas holds, we know, that a man may rightfully be wiser today than he was yesterday-that he may rightfully change when he finds himself wrong.

            But, can we for that reason, run ahead, and infer that he will make any particular change, of which he, himself, has given no intimation? Can we safely base our action upon any such vague inference?

            Now, as ever, I wish to not misrepresent Judge Doulgas' position, question his motives, or do aught that can be personally offensive to him.


            Whenever, if ever, he and we can come together on principle so that our great cause may have assistance from his great ability, I hope to have interposed no adventitious obstacle.


            But clearly, he is not now with us-he does not pretend to be-he does not promise to ever be.

            Our cause, then, must be intrusted to, and conducted by its own undoubted friends-those whose hands are free, whose hearts are in the work-who do care for the result.


            Two years ago the Republicans of the nation mustered over thirteen hundred thousand strong.


            We did this under the single impulse of resistance to a common danger, with every external circumstance against us.


            Of strange, discordant, and even, hostile elements, we gathered from the four winds, and formed and fought the battle through, under the constant hot fire of a disciplined, proud, and pampered enemy.

            Did we brave all then to falter now? - now - when that same enemy is wavering, dissevered, and belligerent?


        This result is not doubtful. We shall not fail-if we stand firm, we shall not fail.


            Wise counsels may accelerate or mistakes delay it, but sooner or later the victory is sure to come.";

        private static String LincolnAddressAtIndependenceHall = @"The inaugural journey began in Springfield on February 11 and ended in Washington D. C. on February 23, 1861. In between the train made numerous stops and President-elect Lincoln spoke at many of the stops. one of the more memorable stops occurred at Independence Hall in Philadelphia on George Washington's birthday, February 22.

Source: Neely, Mark E. Jr. 1982. The Abraham Lincoln Encyclopedia. New York: Da Capo Press, Inc.

Independence Hall: Philadelphia, Pennsylvania, February 22, 1861

Mr. CUYLER: I am filled with deep emotion at finding myself standing here, in this place, where were collected together the wisdom, the patriotism, the devotion to principle, from which sprang the institutions under which we live. You have kindly suggested to me that in my hands is the task of restoring peace to the present distracted condition of the country. I can say in return, Sir, that all the political sentiments I entertain have been drawn, so far as I have been able to draw them, from the sentiments which originated and were given to the world from this hall. I have never had a feeling politically that did not spring from the sentiments embodied in the Declaration of Independence. I have often pondered over the dangers which were incurred by the men who assembled here, and framed and adopted that Declaration of Independence. I have pondered over the toils that were endured by the officers and soldiers of the army who achieved that Independence. I have often inquired of myself what great principle or idea it was that kept this Confederacy so long together. It was not the mere matter of the separation of the Colonies from the motherland; but that sentiment in the Declaration of Independence which gave liberty, not alone to the people of this country, but, I hope, to the world, for all future time. It was that which gave promise that in due time the weight would be lifted from the shoulders of all men. This is the sentiment embodied in that Declaration of Independence. Now, my friends, can this country be saved upon that basis? If it can, I will consider myself one of the happiest men in the world if I can help to save it. If it can't be saved upon that principle, it will be truly awful. But, if this country cannot be saved without giving up that principle---I was about to say I would rather be assassinated on this spot than to surrender it. Now, in my view of the present aspect of affairs, there is no need of bloodshed and war. There is no necessity for it. I am not in favor of such a course, and I may say in advance, there will be no blood shed unless it be forced upon the Government. The Government will not use force unless force is used against it. My friends, this is a wholly unprepared speech. I did not expect to be called upon to say a word when I came here---I supposed I was merely to do something towards raising a flag. I may, therefore, have said something indiscreet, but I have said nothing but what I am willing to live by, and, in the pleasure of Almighty God, die by.";

        private static String LincolnSecondInnaguralAddress = @"At this second appearing to take the oath of the presidential office, there is less occasion for an extended address than there was at the first. Then a statement, somewhat in detail, of a course to be pursued, seemed fitting and proper. Now, at the expiration of four years, during which public declarations have been constantly called forth on every point and phrase of the great contest which still absorbs the attention, and engrosses the energies of the nation, little that is new could be presented. The progress of our arms, upon which all else chiefly depends, is as well known to the public as to myself; and it is, I trust, reasonably satisfactory and encouraging to all. With high hope for the future, no prediction in regard to it is ventured.

On the occasion corresponding to this four years ago, all thought were anxiously directed to an impending civil war. All dreaded it - all sought to avert it. While the inaugeral [sic] address was being delivered from this place, devoted altogether to saving the Union without war, insurgent agents were in the city seeking to destroy it without war - seeking to dissole [sic] the Union, and divide effects, by negotiation. Both parties deprecated war; but one of them would make war rather than let the nation survive; and the other would accept war rather than let it perish. And the war came.

One eighth of the whole population were colored slaves, not distributed generally over the Union, but localized in the Southern part o fit. These slaves constituted a peculiar and powerful interest. All knew that this interest was, somehow, the cause of the war. To strengthen, perpetuate, and extend this interest was the object for which the insurgents would rend the Union, even by war; while the government claimed no right to do more than to restrict the territorial enlargement of it. Neither party expected for the war, the magnitude, or the duration, which it has already attained. Neither anticipated that the cause of the conflict might cease with, or even before, the conflict itself should cease. Each looked for an easier triumph, and a result less fundamental and astounding. Both read the same Bible, and pray to the same God; and each invokes His aid against the other. It may seem strange that any men should dare ask a just God's assistance in wringing their bread from the sweat of other men's faces; but let us judge not that we be not judged. The prayers of both could not be answered; that of neither has been answered fully. The Almighty has his own purposes. Woe unto the world because of offences! For it must needs be that offences come; but woe to that man by whom the offence cometh! If we shall suppose that American Slavery is one of those offences which, in the providence of God, must needs come, but which, having continued through His appointed time, he now wills to remove, and that He gives to both North and South, this terrible war, as the woe due to those by whom the offence came, shall we discern therein any departure from those divine attributes which the believers in a Living God always ascribe to Him? Fondly do we hope-fervently do we pray-that this mighty scourge of war may speedily pass away. Yet, if God will that it continue, until all the wealth piled by the bond-man's two hundred and fifty years of unrequited toil shall be sunk, and until every drop of blood drawn with the lash, shall be paid by another drawn with the sword, as was said three thousand years ago, so still it must be said the judgments of the Lord, are true and righteous altogether.

        With malice toward none; with charity for all; with firmness in the right, as God gives us to see the right, let us strive on to finish the work we are in; to bind up the nation's wounds; to care for him who shall have borne the battle, and for his widow, and his orphan - to do all which may achieve and cherish a just and lasting peace, among ourselves, and with all nations.";

        public static IEnumerable<String> Churchill1 => Regex.Split(ChuchillAddressToCongress, @"\s+");
        public static IEnumerable<String> Churchill2 => Regex.Split(ChurchillFiftyYearsHence, @"\s+");
        public static IEnumerable<String> Churchill3 => Regex.Split(ChurchillInvasionOfFrance, @"\s+");

        public static IEnumerable<String> Lincoln1 => Regex.Split(LincolnHouseDivided, @"\s+");
        public static IEnumerable<String> Lincoln2 => Regex.Split(LincolnAddressAtIndependenceHall, @"\s+");
        public static IEnumerable<String> Lincoln3 => Regex.Split(LincolnSecondInnaguralAddress, @"\s+");

        public static IEnumerable<IEnumerable<String>> ChurchillSpeeches => new List<IEnumerable<string>> { Churchill1, Churchill2, Churchill3 };
        public static IEnumerable<IEnumerable<String>> LincolnSpeeches => new List<IEnumerable<string>> { Lincoln1, Lincoln2, Lincoln3 };
    }
}
